name: todos
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"
  
dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ">=0.16.0-nullsafety.0 <2.0.0"
  freezed_annotation: ^2.0.3
  hooks_riverpod: ^1.0.4
  json_annotation: ^4.5.0
  riverpod: ^1.0.3
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  # mockito: ^5.0.5



flutter:
  uses-material-design: true
